# INICIO

GET http://localhost:5000/api/usuario/all



###
# VIEW TODOS CRIADOS
GET {{host}}/clientes
Content-Type: application/json



###
# CRIAR 1º
POST {{host}}/criar_cliente
Content-Type: application/json

{
  "id": "1",
  "nome": "admin",
  "email": "admin@email.com",
  "password": "123"
}

###
# 
